plugins {
    id 'org.springframework.boot'
}

dependencies {

    //Rest and web client
    implementation 'org.springframework.boot:spring-boot-starter-web:4.1.0'

    //Open API
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.3")

    // Dependencias de otros módulos
    implementation project(':juarez-common')
    implementation project(':juarez-domain')
    implementation project(':juarez-application')
    implementation project(':juarez-infrastructure')
}