plugins {
    id 'java-library'
}

dependencies {
    // General modules dependencies
    api project(':juarez-common')
    api project(':juarez-domain')
    api project(':juarez-application')

    //SQL
    api 'org.postgresql:postgresql:42.7.8'
    api 'org.springframework.boot:spring-boot-starter-data-jpa:4.1.0'

    //Mongo
    api 'org.springframework.boot:spring-boot-starter-data-mongodb:4.1.0'

    //Redis
    api 'org.springframework.boot:spring-boot-starter-data-redis:4.1.0'
    api 'org.springframework.boot:spring-boot-starter-cache:4.1.0'

    //AWS
    api 'software.amazon.awssdk:s3:2.41.0'

    //Rest and web client
    api 'org.springframework.boot:spring-boot-starter-web:4.1.0'

    //Mail and HTML
    api 'org.springframework.boot:spring-boot-starter-mail:4.1.0'
    api 'org.springframework.boot:spring-boot-starter-thymeleaf:4.1.0'

    // Source: https://mvnrepository.com/artifact/org.projectlombok/lombok
    api("org.projectlombok:lombok:1.18.46")
    // Source: https://mvnrepository.com/artifact/jakarta.validation/jakarta.validation-api
    api("jakarta.validation:jakarta.validation-api:4.0.0-M1")

    //MapStruct
    api 'org.mapstruct:mapstruct:1.6.3'

    annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
}
